# Generated by Django 5.1.5 on 2025-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_tasks_updated_at_taskdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
