# Generated by Django 5.1.5 on 2025-01-31 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
    ]
