# Generated by Django 5.1.5 on 2025-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(to='tasks.employee'),
        ),
    ]
