# Generated by Django 5.1.5 on 2025-03-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset\\defim-1.avif', null=True, upload_to='tasks_asset'),
        ),
    ]
